### PR TITLE
rename test_batch with infer_batch and remove deprecating params

### PR DESCRIPTION
**Pull request by adpartin**
Fixing #65 
Fixing #66

### CODE REVIEW

**Comment by jonesse3** [comment]
Instead of deprecating variables, can we just remove them?

**Comment by nkoussa** [comment]
@adpartin Maybe we can discuss today, but I've been thinking (especially through the lens of writing documentation stuff) and I don't think we should have hidden/suppressed parameters. I think we should be clear about what parameters are used for what and when with this release/curation-update to prevent future issues.

**Comment by adpartin** [comment]
Sure, let's discuss it.

**Comment by adpartin** [comment]
@jonesse3 @nkoussa removed deprecated params.

**Review by nkoussa — APPROVED** [review]

**Pull request merged**
