### PR TITLE
Wilke/conflict of types 43

### LINKED ISSUE #43: Conflict of types when parameters read in via config or cli
Currently, config and cli values are read in as string type. @adpartin added a function` cast_value` in `improvelib/utils.py`. See commit of the fix: https://github.com/JDACS4C-IMPROVE/IMPROVE/commit/4c2aacc4bf850bdba100f069b0a53216d81e257e. @priyanka9991 observed a similar issue with list types.

@wilke Is there another efficient way to check types?

I can add a unit test to check types for different parameters when read in as default, config, or cli.

### LINKED ISSUE #56: Missing dict attribute in config
Refactoring is not done properly:

Traceback (most recent call last):
  File "config.py", line 425, in <module>
    print(cfg.dict())
AttributeError: 'Config' object has no attribute 'dict'

### PR DESCRIPTION
**Pull request by wilke**
Reading values from config file.  Setting defaults for command line options based on values from the config file.

Fixes #43 
Fixes #56

### CODE REVIEW

**Comment by wilke** [comment]
I did not run the unit test.

**Comment by jonesse3** [comment]
Ran unit test. Need to add list type. Not sure why True is not being read in properly. 

======================================================================
FAIL: test_infer_config_type_boolean (test_params.TestTypeInferConfigs)
INFER: Check type for boolean parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 405, in test_infer_config_type_boolean
    self.assertIsInstance(infer_params['only_cross_study'], bool)
AssertionError: 'True' is not an instance of <class 'bool'>

======================================================================
FAIL: test_infer_config_type_list (test_params.TestTypeInferConfigs)
INFER: Check type for list parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 399, in test_infer_config_type_list
    self.assertIsInstance(infer_params['split'], list)
AssertionError: '[2,3]' is not an instance of <class 'list'>

======================================================================
FAIL: test_preprocess_config_type_boolean (test_params.TestTypePreprocessConfigs)
PREPROCESS: Check type for boolean parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 201, in test_preprocess_config_type_boolean
    self.assertIsInstance(preprocess_params['only_cross_study'], bool)
AssertionError: 'True' is not an instance of <class 'bool'>

======================================================================
FAIL: test_preprocess_config_type_list (test_params.TestTypePreprocessConfigs)
PREPROCESS: Check type for list parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 195, in test_preprocess_config_type_list
    self.assertIsInstance(preprocess_params['split'], list)
AssertionError: '[2,3]' is not an instance of <class 'list'>

======================================================================
FAIL: test_train_config_type_boolean (test_params.TestTypeTrainConfigs)
TRAIN: Check type for boolean parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 303, in test_train_config_type_boolean
    self.assertIsInstance(train_params['only_cross_study'], bool)
AssertionError: 'True' is not an instance of <class 'bool'>

======================================================================
FAIL: test_train_config_type_list (test_params.TestTypeTrainConfigs)
TRAIN: Check type for list parameter in config_file_2.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/lambda_stor_01/homes/ac.sejones/test_improve_library/IMPROVE/tests/test_params.py", line 297, in test_train_config_type_list
    self.assertIsInstance(train_params['split'], list)
AssertionError: '[2,3]' is not an instance of <class 'list'>

----------------------------------------------------------------------

**Comment by wilke** [comment]
@jonesse3 Can we check both code bases? If i use initialize_parameters and print the types of the command line arguments, I get the correct types.

**Comment by jonesse3** [comment]
What does your config file look like?

**Comment by wilke** [comment]
We are missing specific tests for Config. The current tests are for DRP*

**Comment by wilke** [comment]
python test_params.py

----------------------------------------------------------------------
Ran 63 tests in 0.199s

OK

**Comment by wilke** [comment]
fixes #79

**Pull request merged**
