### PR TITLE
Update Parsl-CSA readme and Update download_csa.sh with updated wget command

### PR DESCRIPTION
**Pull request by priyanka9991**
Update Parsl-CSA readme and update download_csa.sh with new wget command from @jonesse3 in #145

### CODE REVIEW

**Comment by adpartin** [comment]
@priyanka9991 I didn't test it, but I assume it works so I ready to approve. However, in order to mitigate redundancy, would it make more sense to put `download_csa.sh` in `https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/priyanka/fixes/scripts` because `download_csa.sh` is relevant both in parsl_csa and bruteforce_csa?

**Comment by priyanka9991** [comment]
@adpartin Yes I agree. I have made changes to scripts/get_benchmarks and used it to download CSA data for parsl CSA. Parsl_csa Readme has also been updated and removed download_csa.sh from parsl_csa.
Please check the changes in scripts/get_benchmarks and workflows/parsl_csa/Readme.md
I have tested this in GraphDRP.

**Comment by priyanka9991** [comment]
> @priyanka9991 I didn't test it, but I assume it works so I ready to approve. However, in order to mitigate redundancy, would it make more sense to put `download_csa.sh` in `https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/priyanka/fixes/scripts` because `download_csa.sh` is relevant both in parsl_csa and bruteforce_csa?

If we put download_csa.sh in `https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/priyanka/fixes/scripts` I feel it is redundant since it does the same thing as scripts/get-benchmarks. We should decide on how we want to name the benchmark data download script.

**Comment by adpartin** [comment]
@priyanka9991 I'm not sure why we need `get-benchmarks`. But if for any reason we do, we can have both `get-benchmarks.sh` and `download_csa.sh` inside `scripts`, and then call for `download_csa.sh` from `get-benchmarks`. Any thoughts?

**Comment by priyanka9991** [comment]
> @priyanka9991 I'm not sure why we need `get-benchmarks`. But if for any reason we do, we can have both `get-benchmarks.sh` and `download_csa.sh` inside `scripts`, and then call for `download_csa.sh` from `get-benchmarks`. Any thoughts?

Both `get-benchmarks` and `download_csa.sh` scripts download the CSA benchmark data. 
I like the style of get-benchmarks better because it has option to specify the destination for downloading the data. Also the updated 'get-benchmarks' (https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/priyanka/fixes/scripts/get-benchmarks) combines both `get-benchmarks` and `download_csa.sh` and takes in the destination directory, checks for existing directory and starts data download (excluding .index) files. 

I feel we do not need both `get-benchmarks` and `download_csa.sh`. We can choose how we want to name the script.

**Review by adpartin — APPROVED** [review]

**Review by adpartin — DISMISSED** [review]

**Comment by priyanka9991** [comment]
@adpartin I have uploaded the download_csa.sh and updated get_benchmarks.

**Review by adpartin — APPROVED** [review]

**Pull request merged**
